# reset-passwordless-sudo
---
# Assumptions:
# - Remote jhed user is already configured on target host(s) with sudo privileges (but sudo requires password).

- name: "If not vagrant, check if PBIS is active"
  block:
  - name: "Check if PBIS is active"
    become: true
    shell: "/opt/pbis/bin/domainjoin-cli query | egrep 'OU=MSEL-LinuxServers,OU=MSEL-Cells,OU=MSEL,DC=win,DC=ad,DC=jhu,DC=edu' | wc -l"
    register: pbis_installed

  - name: "Die if pbis not installed"
    meta: end_play
    when: pbis_installed.stdout == "0"
  when: not using_vagrant
# --------------------------------------- 
#
- set_fact:
  login_group_sudoers: "ALL=(ALL) PASSWD: ALL"

- name: create temporary sudoers file for login user
  copy:
    dest: "/tmp/sudoers_{{ login_group }}.edit"
    content: "%{{ login_group }} {{ login_group_sudoers }}"
  become: true

- name: validate and implement edits
  copy:
    src: "/tmp/sudoers_{{ login_group }}.edit"
    dest: "/etc/sudoers.d/{{ login_group }}"
    validate: 'visudo -cf %s'
    remote_src: true
    mode: "u=r,g=r,o-rwx" #0440
  become: true

- name: cleanup temp file
  file:
    path: "/tmp/sudoers_{{ login_user }}.edit"
    state: absent
  become: true
