# Assumptions:
# - Vagrant setup
#
---

- name: "Check if PBIS is installed "
  ansible.builtin.stat:
    path: "/opt/pbis/bin/domainjoin-cli"
  register: pbis

- name:
  ansible.builtin.fail:
    msg: "PBIS is installed. This does not appear to be a vagrant setup. Exiting!"
  when: pbis.stat.exists

- name: "Add login user's group."
  group:
    name: "{{ login_group }}"
    gid:  "{{ login_group_gid | default(omit) }}"
    state: present
  become: true

- name: "Add login user."
  user:
    name: "{{ login_user }}"
    shell: "/bin/bash"
    uid:    "{{ login_user_uid | default(omit) }}"
    group:  "{{ login_group | default(omit)  }}"
  become: true

- name: "Upload ssh key for login user."
  authorized_key:
    user: "{{ login_user }}"
    key: "{{ lookup('file', '{{ sshkey_dir }}/{{ sshkey_name }}') }}"
    state: present
  become: true

- name: configure sudo
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ login_group }}"
    create: yes
    state: present
    line: "%{{ login_group }} ALL=(ALL) NOPASSWD: ALL"
    owner: root
    group: root
    mode: '0440'
  become: true

...
