---
# Assumptions:
# - Remote jhed user is already configured on target host(s) with sudo privileges (but sudo requires password).
# Sudo privs are configured in /etc/sudoers.d/<login_group>
# No other setup is supported

- name: Remove password requirement from sudoers
  ansible.builtin.replace:
  become: true
    path: "/etc/sudoers.d/{{ login_group }}"
    regexp: " PASSWD:"
    replace: " NOPASSWD:" 

