---
# Assumptions:
# - Vagrant setup

#- name: gather facts
#  setup:
#  register: facts
#
## verbosity level of 3 requires the play to be run with -vvv to output the debug data
#- name: report facts
#  debug:
#    var: facts
#    verbosity: 3

- name: "Add login user's group."
  group:
    name: "{{ login_group }}"
    gid:  "{{ login_group_gid | default(omit) }}"
    state: present
  become: true
  when: using_vagrant

- name: "Add login user."
  user:
    name: "{{ login_user }}"
    shell: "/bin/bash"
    uid:    "{{ login_user_uid | default(omit) }}"
    group:  "{{ login_group | default(omit)  }}"
  become: true
  when: using_vagrant

- name: "Upload ssh key for login user."
  authorized_key:
    user: "{{ login_user }}"
    key: "{{ lookup('file', '{{ sshkey_dir }}/{{ sshkey_name }}') }}"
    state: present
  become: true
  when: using_vagrant

- name: configure sudo
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ login_group }}"
    create: yes
    state: present
    line: "%{{ login_group }} ALL=(ALL) NOPASSWD: ALL"
    owner: root
    group: root
    mode: '0440'
  become: true
  when: using_vagrant

---
